global using System;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using printing_om_and_pm_system_app.Models;
global using printing_om_and_pm_system_app.Db;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Authorization;
// global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using printing_om_and_pm_system_app.Repositories;
global using printing_om_and_pm_system_app.Models;
global using printing_om_and_pm_system_app.Db;
global using printing_om_and_pm_system_app.DTO.Incoming;
global using printing_om_and_pm_system_app.DTO.Outgoing;
global using AutoMapper;
global using System.Text.Json.Serialization;